name: build

on: [push]

jobs:
  build:
    name: Test Plugin

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          working-directory: test/fixtures/blog

      - uses: pnpm/action-setup@v1.2.1
        with:
          version: 5.13.6
          run_install: |
            - recursive: false

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test

      - name: Lint
        run: pnpm lint
